using System.Collections.Generic;
using System.Data.Entity;

namespace WebApiODataPagination.Models
{
    public class AppDbInitializer : DropCreateDatabaseAlways<AppContext>
    {
        protected override void Seed(AppContext context)
        {
            var customers = new List<Customer>()
            {
                new Customer() {Name= "Kevyn", LastName= "Brown", Email= "fringilla.cursus@at.ca"},
	            new Customer() {Name= "Emery", LastName= "Mcclure", Email= "quam@fames.net"},
	            new Customer() {Name= "Seth", LastName= "Patrick", Email= "adipiscing.elit@nec.net"},
	            new Customer() {Name= "Lawrence", LastName= "Wilcox", Email= "ridiculus@NulladignissimMaecenas.ca"},
	            new Customer() {Name= "Ferdinand", LastName= "Herring", Email= "id@velpedeblandit.org"},
	            new Customer() {Name= "Omar", LastName= "Henry", Email= "nec.leo.Morbi@eu.co.uk"},
	            new Customer() {Name= "Ina", LastName= "Peck", Email= "nec@Maecenas.co.uk"},
	            new Customer() {Name= "Adara", LastName= "Morse", Email= "ornare.libero@nibhsitamet.co.uk"},
	            new Customer() {Name= "Zeus", LastName= "Hamilton", Email= "tincidunt.nunc.ac@dui.com"},
	            new Customer() {Name= "Ramona", LastName= "Finley", Email= "tempor@non.edu"},
	            new Customer() {Name= "Calista", LastName= "Lindsay", Email= "Ut@Fusce.com"},
	            new Customer() {Name= "Orson", LastName= "Barber", Email= "fringilla@morbitristiquesenectus.ca"},
	            new Customer() {Name= "Halla", LastName= "Sims", Email= "bibendum.fermentum.metus@ut.net"},
	            new Customer() {Name= "Colt", LastName= "Fuller", Email= "dictum.eleifend@Nullamvitae.co.uk"},
	            new Customer() {Name= "Ciaran", LastName= "Tran", Email= "lacinia@dolor.org"},
	            new Customer() {Name= "Odette", LastName= "Martin", Email= "eu.ultrices.sit@nonantebibendum.com"},
	            new Customer() {Name= "Donna", LastName= "Duke", Email= "laoreet.libero@inhendrerit.net"},
	            new Customer() {Name= "Raymond", LastName= "Marks", Email= "sit.amet.consectetuer@erat.com"},
	            new Customer() {Name= "Abra", LastName= "Rush", Email= "luctus.felis.purus@ultrices.net"},
	            new Customer() {Name= "Colt", LastName= "Sims", Email= "ultrices@InloremDonec.co.uk"},
	            new Customer() {Name= "Chantale", LastName= "Strickland", Email= "facilisis.facilisis.magna@erat.edu"},
	            new Customer() {Name= "Quincy", LastName= "Goodwin", Email= "a.arcu@ligulaAenean.edu"},
	            new Customer() {Name= "Beatrice", LastName= "Burks", Email= "nostra.per.inceptos@nasceturridiculusmus.org"},
	            new Customer() {Name= "Eleanor", LastName= "Russo", Email= "nulla.vulputate.dui@ipsumnunc.org"},
	            new Customer() {Name= "Virginia", LastName= "Buchanan", Email= "vitae.mauris@montes.com"},
	            new Customer() {Name= "Nell", LastName= "Miller", Email= "feugiat.metus.sit@aliquamiaculis.com"},
	            new Customer() {Name= "Dennis", LastName= "Garcia", Email= "Sed.pharetra@libero.edu"},
	            new Customer() {Name= "Remedios", LastName= "Pacheco", Email= "turpis.nec.mauris@nullaIntegervulputate.org"},
	            new Customer() {Name= "Erica", LastName= "Hunt", Email= "tincidunt.neque.vitae@eueleifend.edu"},
	            new Customer() {Name= "Silas", LastName= "Stein", Email= "Quisque.fringilla@nasceturridiculus.net"},
	            new Customer() {Name= "Donna", LastName= "Webster", Email= "eros@nullaDonec.co.uk"},
	            new Customer() {Name= "Allistair", LastName= "Hester", Email= "nunc.sit.amet@nonummy.org"},
	            new Customer() {Name= "Jason", LastName= "Durham", Email= "at.velit.Pellentesque@faucibusut.com"},
	            new Customer() {Name= "Honorato", LastName= "Hill", Email= "aliquet@vestibulumloremsit.net"},
	            new Customer() {Name= "Harrison", LastName= "Lara", Email= "a@acsem.edu"},
	            new Customer() {Name= "Quin", LastName= "Sanford", Email= "Phasellus@enim.co.uk"},
	            new Customer() {Name= "Armando", LastName= "Walters", Email= "at.lacus.Quisque@commodohendreritDonec.edu"},
	            new Customer() {Name= "Rajah", LastName= "Trevino", Email= "ad.litora.torquent@tristique.edu"},
	            new Customer() {Name= "Shana", LastName= "Shepard", Email= "lacinia@ipsumdolorsit.org"},
	            new Customer() {Name= "Shelby", LastName= "Payne", Email= "Quisque.ornare.tortor@risus.ca"},
	            new Customer() {Name= "Keiko", LastName= "Solomon", Email= "Aliquam@urnaconvallis.edu"},
	            new Customer() {Name= "Darrel", LastName= "Wells", Email= "nec@feugiatnonlobortis.org"},
	            new Customer() {Name= "Tasha", LastName= "Lawrence", Email= "cursus@estNuncullamcorper.co.uk"},
	            new Customer() {Name= "Sloane", LastName= "Tillman", Email= "a.feugiat@Crasdolordolor.co.uk"},
	            new Customer() {Name= "Breanna", LastName= "Espinoza", Email= "tellus.Suspendisse@sagittissemperNam.com"},
	            new Customer() {Name= "Ciaran", LastName= "Caldwell", Email= "vehicula.et@pede.com"},
	            new Customer() {Name= "Randall", LastName= "Schroeder", Email= "bibendum.Donec.felis@imperdiet.edu"},
	            new Customer() {Name= "Veronica", LastName= "Pugh", Email= "tristique.ac.eleifend@quisurnaNunc.edu"},
	            new Customer() {Name= "Aiko", LastName= "Morse", Email= "neque.sed@Suspendisse.com"},
	            new Customer() {Name= "Jelani", LastName= "Calderon", Email= "at.fringilla@aliquamarcuAliquam.ca"},
	            new Customer() {Name= "Frances", LastName= "Dalton", Email= "gravida@ut.co.uk"},
	            new Customer() {Name= "Zephr", LastName= "Wolfe", Email= "Aliquam.gravida@Integervulputate.org"},
	            new Customer() {Name= "Hannah", LastName= "Yates", Email= "odio.Phasellus.at@sitamet.co.uk"},
	            new Customer() {Name= "Levi", LastName= "Morrison", Email= "volutpat@utnullaCras.org"},
	            new Customer() {Name= "Jaquelyn", LastName= "Hunt", Email= "vitae.risus.Duis@Sedetlibero.net"},
	            new Customer() {Name= "Doris", LastName= "Kelly", Email= "ligula.Nullam.enim@rutrumurna.org"},
	            new Customer() {Name= "Madison", LastName= "Schroeder", Email= "per@diamluctuslobortis.ca"},
	            new Customer() {Name= "Avye", LastName= "Hodges", Email= "magna.Praesent.interdum@aodiosemper.net"},
	            new Customer() {Name= "Illiana", LastName= "Burns", Email= "purus.accumsan@sagittisDuis.co.uk"},
	            new Customer() {Name= "Lyle", LastName= "Ball", Email= "ligula.Nullam.enim@veliteusem.edu"},
	            new Customer() {Name= "Cody", LastName= "Harrington", Email= "lorem.Donec.elementum@urnaUt.edu"},
	            new Customer() {Name= "Britanney", LastName= "Klein", Email= "vehicula.Pellentesque.tincidunt@arcu.org"},
	            new Customer() {Name= "Amir", LastName= "Guerrero", Email= "semper.rutrum.Fusce@eleifendCras.edu"},
	            new Customer() {Name= "Lewis", LastName= "French", Email= "ac.turpis@commodo.co.uk"},
	            new Customer() {Name= "Brianna", LastName= "Webb", Email= "malesuada@odiosagittis.co.uk"},
	            new Customer() {Name= "Selma", LastName= "Kirk", Email= "ipsum@utdolordapibus.org"},
	            new Customer() {Name= "Alisa", LastName= "Reeves", Email= "bibendum@auctornonfeugiat.com"},
	            new Customer() {Name= "Chancellor", LastName= "Bennett", Email= "lorem@pharetraNam.co.uk"},
	            new Customer() {Name= "Tobias", LastName= "Anthony", Email= "ipsum.non@non.ca"},
	            new Customer() {Name= "Joshua", LastName= "Ball", Email= "vel@feugiat.co.uk"},
	            new Customer() {Name= "Mariam", LastName= "Mckenzie", Email= "laoreet.lectus.quis@Quisque.ca"},
	            new Customer() {Name= "Garrett", LastName= "Powell", Email= "blandit.viverra.Donec@euduiCum.edu"},
	            new Customer() {Name= "Hasad", LastName= "Woodward", Email= "nec.imperdiet.nec@Pellentesque.com"},
	            new Customer() {Name= "Anne", LastName= "Phelps", Email= "Etiam@velarcu.ca"},
	            new Customer() {Name= "Keane", LastName= "Oneil", Email= "fringilla.cursus.purus@ullamcorperDuiscursus.edu"},
	            new Customer() {Name= "Magee", LastName= "Woodard", Email= "odio.auctor@erateget.edu"},
	            new Customer() {Name= "Alyssa", LastName= "Ramos", Email= "iaculis.odio@Integertincidunt.co.uk"},
	            new Customer() {Name= "Cailin", LastName= "Landry", Email= "vulputate@Aliquamultrices.edu"},
	            new Customer() {Name= "Kathleen", LastName= "Merrill", Email= "Mauris.ut.quam@tinciduntnibhPhasellus.net"},
	            new Customer() {Name= "Donovan", LastName= "Drake", Email= "Phasellus.at@sitamet.edu"},
	            new Customer() {Name= "Bruce", LastName= "Chang", Email= "nulla@condimentumDonec.com"},
	            new Customer() {Name= "Neve", LastName= "Abbott", Email= "eleifend.egestas.Sed@Aliquamultricesiaculis.org"},
	            new Customer() {Name= "Dexter", LastName= "Price", Email= "Nulla.eget.metus@tristiqueac.org"},
	            new Customer() {Name= "Chadwick", LastName= "Hammond", Email= "sociosqu@Nuncmauris.com"},
	            new Customer() {Name= "Oprah", LastName= "Coffey", Email= "eget.varius@sociis.co.uk"},
	            new Customer() {Name= "Urielle", LastName= "Beasley", Email= "vel.arcu@odiosagittissemper.co.uk"},
	            new Customer() {Name= "Shad", LastName= "Oneil", Email= "pede@amet.org"},
	            new Customer() {Name= "Kyla", LastName= "Pacheco", Email= "est.tempor@Sed.ca"},
	            new Customer() {Name= "Natalie", LastName= "Alvarez", Email= "dictum@Aliquamauctorvelit.ca"},
	            new Customer() {Name= "Galena", LastName= "Donovan", Email= "Fusce.feugiat@duiCumsociis.net"},
	            new Customer() {Name= "Yoshi", LastName= "Tyler", Email= "non.luctus.sit@risusMorbimetus.com"},
	            new Customer() {Name= "Graiden", LastName= "Dominguez", Email= "pharetra@Maurisvestibulumneque.co.uk"},
	            new Customer() {Name= "Dawn", LastName= "Lewis", Email= "est.Mauris.eu@cursuseteros.co.uk"},
	            new Customer() {Name= "Hayes", LastName= "Long", Email= "nibh.Quisque.nonummy@luctussit.co.uk"},
	            new Customer() {Name= "Jonah", LastName= "Chan", Email= "et@Vestibulumut.com"},
	            new Customer() {Name= "Melanie", LastName= "Farley", Email= "dignissim.magna.a@erat.net"},
	            new Customer() {Name= "Noah", LastName= "Todd", Email= "blandit.Nam.nulla@egetipsum.co.uk"},
	            new Customer() {Name= "Alexa", LastName= "Hines", Email= "vestibulum@lorem.com"},
	            new Customer() {Name= "Mark", LastName= "Swanson", Email= "non@odio.co.uk"},
	            new Customer() {Name= "Anastasia", LastName= "Gamble", Email= "eu@Namconsequatdolor.org"}
            };

            context.Customers.AddRange(customers);
            context.SaveChanges();
        }
    }
}
